language: python
sudo: false
cache: pip

python:
  - "3.5"

addons:
  # By default postgresql-9.1 is installed but there is issue related:
  #  https://github.com/OCA/maintainer-quality-tools/issues/432#issuecomment-281580935
  # Better use higher PostgreSQL version
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

env:
  global:
  - VERSION="11.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="OCA/OCB"
  - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1"


install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools --depth=1
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
